# Javascript Node CircleCI 2.0 configuration file
#

jobs:
  test-job:
    docker:
      - image: "cimg/node:lts"

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run: yarn setup

      - save_cache:
          paths:
            - node_modules
            - client/node_modules
            - server/node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          command: yarn lint

      - run:
          command: yarn test
          environment:
            TZ: UTC
            VITE_COMMIT_SHA: some_sha

      - store_artifacts: # For coverage report
          path: client/coverage

orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1

workflows:
  tests:
    jobs:
      - test-job
