#!/bin/bash
WIREGUARD_INTERFACE=IPV6ADMINS
WIREGUARD_LAN=192.168.30.1/24
WIREGUARD_LAN_IPV6=2001:db8:30:1::/64
MASQUERADE_INTERFACE=eth0

CHAIN_NAME="WIREGUARD_$WIREGUARD_INTERFACE"

iptables -t nat -D POSTROUTING -o $MASQUERADE_INTERFACE -j MASQUERADE -s $WIREGUARD_LAN
ip6tables -t nat -D POSTROUTING -o $MASQUERADE_INTERFACE -j MASQUERADE -s $WIREGUARD_LAN_IPV6

# Remove and delete the WIREGUARD_wg0 chain
iptables -D FORWARD -j $CHAIN_NAME
iptables -F $CHAIN_NAME
iptables -X $CHAIN_NAME

# Remove and delete the WIREGUARD_wg0 chain
ip6tables -D FORWARD -j $CHAIN_NAME
ip6tables -F $CHAIN_NAME
ip6tables -X $CHAIN_NAME